spring:
    application:
        name: payment-service
server:
    port: 8080
cassandra:
  keyspace: ${vcap.services.payment-db.credentials.keyspace_name:default_info}
  contactPoints: ${vcap.services.payment-db.credentials.node_ips:localhost}
  user: ${vcap.services.payment-db.credentials.username:u}
  pwd: ${vcap.services.payment-db.credentials.password:p}